server:
  port: 8082

spring:
  application:
    name: user-management-service
  config:
    import: consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

  cloud:
    consul:
      discovery:
       # preferIpAddress: true
        instanceId: ${spring.application.name}:${random.value}
        deregister: true

